CREATE DATABASE DB_VIDEOLOCA

CREATE TABLE CLIENTES
(
	COD_CLIENTE NUMERIC(18,0) PRIMARY KEY NOT NULL,
	RG VARCHAR2(9) NOT NULL,
	NOME VARCHAR2(50) NOT NULL,
	ENDERECO VARCHAR2(50) NULL,
	BAIRRO VARCHAR2(30) NULL,
	CIDADE VARCHAR2(30) NULL, 
	ESTADO CHAR(2) NOT NULL,
	TELEFONE VARCHAR2(15) NULL,
	EMAIL VARCHAR2(30) NULL,
	DATANASCIMENTO DATE NULL,
	sexo CHAR(1)
)


CREATE TABLE CATEGORIA
(
	COD_CATEGORIA NUMERIC(10,0) PRIMARY KEY NOT NULL,
	NOME_CATEGORIA VARCHAR(20) NOT NULL
)

CREATE TABLE FILME
(
	COD_FILME NUMERIC(18,0) PRIMARY KEY NOT NULL,
	TITULO VARCHAR(30) NOT NULL,
	COD_CATEGORIA NUMERIC(10,0) NOT NULL,
	DIRETOR VARCHAR(50) NOT NULL,
	VALOR_LOCACAO FLOAT NOT NULL,
	RESERVADA CHAR(1) NOT NULL
)

CREATE TABLE LOCACOES
(
	COD_LOCACAO NUMERIC(18,0) NOT NULL,
	COD_CLIENTE NUMERIC(18,0) NOT NULL,
	COD_FILME NUMERIC(18,0) NOT NULL,
	DATA_RETIRADA DATE NOT NULL,
	DATA_DEVOLUCAO DATE NULL,
	CONSTRAINT PK_LOCACAO_CLIENTE PRIMARY KEY(COD_LOCACAO, COD_CLIENTE, COD_FILME)
)


--CRIAÇÃO DOS RELACIONAMENTOS 
--LOCACAO - CLIENTES
ALTER TABLE LOCACOES ADD CONSTRAINT FK_LOCACOES_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTES(COD_CLIENTE)


-- LOCACOES - FILME
ALTER TABLE LOCACOES ADD CONSTRAINT FK_LOCACOES_FILME FOREIGN KEY (COD_FILME) REFERENCES FILME(COD_FILME)


--FILME - CATEGORIA
ALTER TABLE FILME ADD CONSTRAINT FK_CATEGORIA_FILME FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA(COD_CATEGORIA)


-- SEQUENCE

CREATE SEQUENCE LOCACOES_SEQ MINVALUE 1 MAXVALUE 9999 START WITH 1 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE FILME_SEQ MINVALUE 1 MAXVALUE 9999 START WITH 1 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE CATEGORIA_SEQ MINVALUE 1 MAXVALUE 9999 START WITH 1 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE CLIENTES_SEQ MINVALUE 1 MAXVALUE 9999 START WITH 1 INCREMENT BY 1 CACHE 20;



-- INSERÇÕES NAS TABELAS
--categoria
INSERT INTO CATEGORIA(COD_CATEGORIA,NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL,'Ação');
INSERT INTO CATEGORIA(COD_CATEGORIA,NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL,'Romance');
INSERT INTO CATEGORIA(COD_CATEGORIA,NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL,'Aventura');
INSERT INTO CATEGORIA(COD_CATEGORIA,NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL,'Ficção');
INSERT INTO CATEGORIA(COD_CATEGORIA,NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL,'Drama');
INSERT INTO CATEGORIA(COD_CATEGORIA,NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL,'Terror');
INSERT INTO CATEGORIA(COD_CATEGORIA,NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL,'Desenho');
INSERT INTO CATEGORIA(COD_CATEGORIA,NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL,'Policial');
INSERT INTO CATEGORIA(COD_CATEGORIA,NOME_CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL,'Comédia');


--clientes
INSERT INTO CLIENTES(COD_CLIENTE,RG,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,TELEFONE,EMAIL,DATANASCIMENTO,sexo) VALUES (CLIENTES_SEQ.NEXTVAL,'321346530', 'Edson Martin Feitosa', 'Rua Orlando Alvarenga, 1', 'Jd. Vera Cruz', 'Sorocaba', 'SP', '32125809', 'edson.feitosa@ig.com.br', '30-05-2019', 'M');
INSERT INTO CLIENTES(COD_CLIENTE,RG,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,TELEFONE,EMAIL,DATANASCIMENTO,sexo) VALUES (CLIENTES_SEQ.NEXTVAL,'421346111', 'Rafael Fernando de Moraes Moreno', 'Rua Francisco de Souza, 123', 'Jd. Nova Esperança', 'São Roque', 'SP', '32274567', 'rafael@terra.com.br', '01-04-1985', 'M');
INSERT INTO CLIENTES(COD_CLIENTE,RG,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,TELEFONE,EMAIL,DATANASCIMENTO,sexo) VALUES (CLIENTES_SEQ.NEXTVAL,'324857670', 'João da Silva', 'Rua Mario Quintana, 13', 'Av. Bartolomeu', 'Sorocaba', 'SP', '32134098', 'joao@uol.com.br', '12-05-1992', 'M');
INSERT INTO CLIENTES(COD_CLIENTE,RG,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,TELEFONE,EMAIL,DATANASCIMENTO,sexo) VALUES (CLIENTES_SEQ.NEXTVAL,'112345553', 'Maria Chiquinha', 'Rua Padre Luiz, 55', 'Jd. Vera Cruz', 'Sorocaba', 'SP', '23336684', 'maria@ig.com.br', '30-11-1982', 'F');
INSERT INTO CLIENTES(COD_CLIENTE,RG,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,TELEFONE,EMAIL,DATANASCIMENTO,sexo) VALUES (CLIENTES_SEQ.NEXTVAL,'945848768', 'Rafael Nunes Sales', 'Rua Orlando Alvarenga, 4', 'Jd. Vera Cruz', 'Sorocaba', 'SP', '32124609', 'rafael.sales@terra.com.br', '01-04-1985', 'M');
INSERT INTO CLIENTES(COD_CLIENTE,RG,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,TELEFONE,EMAIL,DATANASCIMENTO,sexo) VALUES (CLIENTES_SEQ.NEXTVAL,'676548499', 'Daniela Martin Feitosa', 'Rua Guilherme Oliveria, 1', 'Jd. Vera das Acássicas', 'Votorantim', 'SP', '32132109', 'daniela.martin@gmail.com', '26-12-1984', 'F');
INSERT INTO CLIENTES(COD_CLIENTE,RG,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,TELEFONE,EMAIL,DATANASCIMENTO,sexo) VALUES (CLIENTES_SEQ.NEXTVAL,'321349999', 'Renata Cristina', 'Rua Orlando Alvarenga, 1', 'Jd. Vera Cruz', 'Sorocaba', 'SP', '32125809', 'renata@gmail', '01-09-1970', 'F');
INSERT INTO CLIENTES(COD_CLIENTE,RG,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,TELEFONE,EMAIL,DATANASCIMENTO,sexo) VALUES (CLIENTES_SEQ.NEXTVAL,'335466531', 'Joaquim Ferreira de Souza Junior', 'Rua Outubro Vermelho, 65', 'Jd. Santa Rosália', 'Votorantim', 'SP', '11125809', 'joaquim_junior@ig.com.br', '08-04-1985', 'M');
INSERT INTO CLIENTES(COD_CLIENTE,RG,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,TELEFONE,EMAIL,DATANASCIMENTO,sexo) VALUES (CLIENTES_SEQ.NEXTVAL,'112233445', 'Ladislau Ferreira', 'Rua Orlando Alvarenga, 12345', 'Jd. Vera Cruz', 'Sorocaba', 'SP', '32144409', 'ladislau@terra.com.br', '03-01-1968', 'M');
INSERT INTO CLIENTES(COD_CLIENTE,RG,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,TELEFONE,EMAIL,DATANASCIMENTO,sexo) VALUES (CLIENTES_SEQ.NEXTVAL,'222222222', 'Vanessa Oliveira', 'Rua das Flores, 1', 'Jd. do Sol', 'Votorantim', 'SP', '32122222', 'vanessa@ig.com.br', '05-04-1965', 'F');



--filmes
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'300', 1, 'Richard Donner', 3.5, 'n');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Máquina Mortífera', 1, 'Richard Donner', 3.6, 'n');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'A Mexicana', 2, 'Burr Steers', 2, 's');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'A Verdade Nua e Crua', 2, 'Robert Luketic', 4, 'n');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'A vida é bela', 2, 'Roberto Benigni', 3.5, 's');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Austrália', 3, 'Baz Luhrmann', 4, 's');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Ultimato Bourn', 3, 'Paul Greengrass', 3.5, 'n');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Constantine', 4, 'Francis Lawrence', 2.5, 's');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Os Irmãos Grimm', 4, 'Terry Gilliam', 3.5, 'n');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Os Doze Macacos', 4, 'Terry Gilliam', 2.5, 'n');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Amadeus', 5, 'Milos Forman', 10, 'n');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'As Torres Gêmeas', 5, 'Oliver Stone', 2.5, 's');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Platoon', 1, 'Oliver Stone', 5.5, 's');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'O Advogado do Diabo', 6, 'Taylor Hackford', 1.5, 's');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Beowulf', 7, 'Robert Zemeckis', 1, 'n');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Bolt o super cão', 7, 'Byron Howard', 1.5, 's');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Apertem o cinto o piloto sumiu', 9, 'Jim Abrahams', 3.6, 's');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Doze é demais', 9, 'Shawn Levy', 9.2, 's');
INSERT INTO FILME (COD_FILME,TITULO,COD_CATEGORIA,DIRETOR,VALOR_LOCACAO,RESERVADA) VALUES (FILME_SEQ.NEXTVAL,'Uma noite no museu', 9, 'Shawn Levy', 2.5, 'n');

DELETE CLIENTES

--Locações
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,9,1, '20-03-2019', '23-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,1,6, '20-03-2019', '23-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,1,8, '20-03-2019', '23-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,1,2, '15-03-2019', '17-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,1,13, '15-03-2019', '17-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,2,5, '20-03-2019', '21-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,3,3, '18-03-2019', '20-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,3,19, '18-03-2019', '20-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,4,17, '01-03-2019', '03-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,5,5, '03-03-2019', '05-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,6,7, '03-03-2019', '04-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,6,9, '03-03-2019', '04-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,7,16, '13-03-2019', '15-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,7,1, '13-03-2019', '15-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,7,5, '14-03-2019', '16-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,7,8, '14-03-2019', '16-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,7,11, '14-03-2019', '16-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,7,12, '15-03-2019', '17-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,8,9, '20-03-2019', '21-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,9,3, '21-03-2019', '22-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,9,6, '21-03-2019', '22-03-2019');
INSERT INTO LOCACOES (COD_LOCACAO,COD_CLIENTE,COD_FILME,DATA_RETIRADA,DATA_DEVOLUCAO) VALUES (LOCACOES_SEQ.NEXTVAL,10,10, '20-03-2019', '21-02-2019');


